apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: elastic-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/rule-type: PathPrefix
spec:
  rules:
  - host: elastic.okstovall.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.elasticsearch.client.service.name }}
          servicePort: 9200
  - host: kibana.okstovall.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.kibana.service.name }}
          servicePort: 5601
