apiVersion: v1
kind: Service
metadata:
  name: kibana-loadbalancer
  namespace: elastic
spec:
  selector:
    app: elasticsearch
    role: kibana
  ports:
  - name: http
    port: 5601
    targetPort: 5601
  type: LoadBalancer