apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ $.Values.cluster.name }}
  namespace: {{ $.Values.namespace }}
spec:
  version: {{ $.Values.cluster.version }}
  http:
    tls:
      selfSignedCertificate: 
        disabled: true
  count: 1
  elasticsearchRef:
    name: {{ $.Values.cluster.name }}
  config:
    monitoring.kibana.collection.enabled: true
  podTemplate:
    metadata:
      annotations:
      {{- range $key, $value := .Values.kibana.annotations }}
        {{ $key }}: {{ quote $value }}
      {{- end}}
        