apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: elasticsearch-masters-discovery-headless
  namespace: elastic
spec:
  clusterIP: None
  ports:
  # - port: 9300
  #   protocol: TCP
  #   targetPort: 9300
  #   name: transport
  - port: 9200
    protocol: TCP
    targetPort: 9200
    name: http
  publishNotReadyAddresses: true
  selector:
    # component: elasticsearch
    app: elasticsearch
    role: master
  sessionAffinity: None
  type: ClusterIP
